# Generated by Django 5.2.6 on 2025-09-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='age_restriction',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_genre',
            field=models.ManyToManyField(related_name='movies', to='movies.genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='movieaudio',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='moviefile',
            name='file',
            field=models.FileField(upload_to='movies/videos'),
        ),
        migrations.AlterField(
            model_name='posterlmage',
            name='image',
            field=models.ImageField(upload_to='movies/posters/'),
        ),
    ]
