# Generated by Django 5.2.6 on 2025-09-09 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_age_restriction_alter_movie_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posterlmage',
            new_name='PosterImage',
        ),
    ]
