# Generated by Django 5.2.6 on 2025-09-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rename_posterlmage_posterimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviefile',
            name='puality',
            field=models.CharField(choices=[('360p', '360p'), ('480p', '480p'), ('720p', '720p'), ('1080p', '1080p'), ('4K', '4K')], default='720p', max_length=10),
        ),
    ]
