# Generated by Django 5.2.6 on 2025-09-13 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_moviefile_puality'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviefile',
            old_name='puality',
            new_name='quality',
        ),
    ]
