# Generated by Django 5.2.6 on 2025-09-16 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_watchsession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WatchSession',
        ),
    ]
